# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric color
format 5 = "%F"
format A 10 2 3
color 1 = @white;@black
color 7 = @white;@blue
rightstring A0 = "date"
rightstring B0 = "item"
rightstring C0 = "price"
rightstring D0 = "total"
let A1 = @dts(2015,11,25)
rightstring B1 = "car"
let C1 = 5000
let D1 = C1
goto D1 A0
