# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric color
format 5 = "%F"
format 6 = " %y-%m-%d %R"
format A 10 2 5
format B 7 0 0
format C 7 3 0
format D 11 2 0
format E 6 3 0
format F 6 2 0
color 1 = @white;@black
color 7 = @white;@blue
rightstring A0 = "date"
rightstring B0 = "milage"
rightstring C0 = "added"
rightstring D0 = "efficiency"
rightstring E0 = "price"
rightstring F0 = "cost"
rightstring G0 = "total"
let A1 = @dts(2015,11,28)
fmt A1 "%F"
let B1 = 197482
let C1 = 16.626
let D1 = @avg(D2:D3)
let E1 = 1.819
let F1 = 30.24
let G1 = F1
let A2 = @dts(2015,12,5)
fmt A2 "%F"
let B2 = 197665
let C2 = 9.541
let D2 = (B2-B1)/C2
let E2 = 1.899
let F2 = 18.12
let G2 = G1+F2
let A3 = @dts(2015,12,12)
fmt A3 "%F"
let B3 = 197806
let C3 = 7.604
let D3 = (B3-B2)/C3
let E3 = 1.799
let F3 = 13.68
let G3 = G2+F3
let A4 = @dts(2016,1,19)
fmt A4 "%F"
let B4 = 197916
let C4 = 8.928
let D4 = (B4-B3)/C4
let E4 = 1.649
let F4 = 14.72
let G4 = G3+F4
rightstring H4 = "low T, in town, heavy load"
let A5 = @dts(2016,1,19)
fmt A5 "%F"
let B5 = 198031
let C5 = 6.119
let D5 = (B5-B4)/C5
let E5 = 1.649
let F5 = 10.09
let G5 = G4+F5
let A6 = @dts(2016,1,21)
fmt A6 "%F"
let B6 = 198193
let C6 = 8.636
let D6 = (B6-B5)/C6
let E6 = 1.599
let F6 = 13.81
let G6 = G5+F6
let A7 = @dts(2016,1,24)
fmt A7 "%F"
let B7 = 198314
let C7 = 6.304
let D7 = (B7-B6)/C7
let E7 = 1.599
let F7 = 10.08
let G7 = G6+F7
let A8 = @dts(2016,2,13)
fmt A8 "%F"
let B8 = 198414
let C8 = 7.256
let D8 = (B8-B7)/C8
let E8 = 1.349
let F8 = 9.79
let G8 = G7+F8
let A9 = @dts(2016,3,1)
fmt A9 "%F"
let B9 = 198659
let C9 = 12.942
let D9 = (B9-B8)/C9
let E9 = 1.699
let F9 = 21.99
let G9 = G8+F9
let A10 = @dts(2016,3,1)
fmt A10 "%F"
let B10 = 198777
let C10 = 5.907
let D10 = (B10-B9)/C10
let E10 = 1.699
let F10 = 10.04
let G10 = G9+F10
let A11 = @dts(2016,3,5)
fmt A11 "%F"
let B11 = 198853
let C11 = 3.936
let D11 = (B11-B10)/C11
let E11 = 1.659
let F11 = 6.53
let G11 = G10+F11
let A12 = @dts(2016,3,10)
fmt A12 "%F"
let B12 = 199034
let C12 = 8.789
let D12 = (B12-B11)/C12
let E12 = 1.799
let F12 = 15.81
let G12 = G11+F12
let A13 = @dts(2016,3,29)
fmt A13 "%F"
let B13 = 199238
let C13 = 10.041
let D13 = (B13-B12)/C13
let E13 = 1.939
let F13 = 19.47
let G13 = G12+F13
let A14 = @dts(2016,3,31)
fmt A14 "%F"
let B14 = 199348
let C14 = 5.732
let D14 = (B14-B13)/C14
let E14 = 1.939
let F14 = 11.11
let G14 = G13+F14
let A15 = @dts(2016,3,31)
fmt A15 "%F"
let B15 = 199483
let C15 = 8.321
let D15 = (B15-B14)/C15
let E15 = 2.299
let F15 = 19.13
let G15 = G14+F15
let A16 = @dts(2016,3,31)
fmt A16 "%F"
let B16 = 199629
let C16 = 9.029
let D16 = (B16-B15)/C16
let E16 = 1.979
let F16 = 17.87
let G16 = G15+F16
let A17 = @dts(2016,4,2)
fmt A17 "%F"
let B17 = 199823
let C17 = 9.338
let D17 = (B17-B16)/C17
let E17 = 1.879
let F17 = 17.55
let G17 = G16+F17
let A18 = @dts(2016,4,2)
fmt A18 "%F"
let B18 = 200100
let C18 = 13.359
let D18 = (B18-B17)/C18
let E18 = 1.949
let F18 = 26.04
let G18 = G17+F18
let A19 = @dts(2016,4,3)
fmt A19 "%F"
let B19 = 200308
let C19 = 10.052
let D19 = (B19-B18)/C19
let E19 = 1.779
let F19 = 17.88
let G19 = G18+F19
let A20 = @dts(2016,4,30)
fmt A20 "%F"
let B20 = 200542
let C20 = 13.288
let D20 = (B20-B19)/C20
let E20 = 1.889
let F20 = 25.1
let G20 = G19+F20
let A21 = @dts(2016,5,23)
fmt A21 "%F"
let B21 = 200960
let C21 = 17.743
let D21 = (B21-B20)/C21
let E21 = 2.073
let F21 = 36.79
let G21 = G20+F21
let A22 = @dts(2016,6,11)
fmt A22 "%F"
let B22 = 201274
let C22 = 14.584
let D22 = (B22-B21)/C22
let E22 = 2.199
let F22 = 32.07
let G22 = G21+F22
let A23 = @dts(2016,6,12)
fmt A23 "%F"
let B23 = 201465
let C23 = 8.416
let D23 = (B23-B22)/C23
let E23 = 2.199
let F23 = 18.51
let G23 = G22+F23
let A24 = @dts(2016,6,25)
fmt A24 "%F"
let B24 = 201772
let C24 = 15.709
let D24 = (B24-B23)/C24
let E24 = 1.999
let F24 = 31.4
let G24 = G23+F24
let A25 = @dts(2016,7,1)
fmt A25 "%F"
let B25 = 202048
let C25 = 12.651
let D25 = (B25-B24)/C25
let E25 = 2.179
let F25 = 27.57
let G25 = G24+F25
let A26 = @dts(2016,7,4)
fmt A26 "%F"
let B26 = 202378
let C26 = 13.836
let D26 = (B26-B25)/C26
let E26 = 2.219
let F26 = 30.7
let G26 = G25+F26
let A27 = @dts(2016,7,4)
fmt A27 "%F"
let B27 = 202643
let C27 = 12.821
let D27 = (B27-B26)/C27
let E27 = 2.159
let F27 = 27.68
let G27 = G26+F27
let A28 = @dts(2016,7,24)
fmt A28 "%F"
let B28 = 202878
let C28 = 12.864
let D28 = (B28-B27)/C28
let E28 = 1.799
let F28 = 23.14
let G28 = G27+F28
let A29 = @dts(2016,8,6)
fmt A29 "%F"
let B29 = 203151
let C29 = 13.693
let D29 = (B29-B28)/C29
let E29 = 1.779
let F29 = 24.36
let G29 = G28+F29
let A30 = @dts(2016,8,20)
fmt A30 "%F"
let B30 = 203363
let C30 = 10.617
let D30 = (B30-B29)/C30
let E30 = 1.999
let F30 = 21.22
let G30 = G29+F30
let A31 = @dts(2016,9,4)
fmt A31 "%F"
let B31 = 203633
let C31 = 12.272
let D31 = (B31-B30)/C31
let E31 = 1.969
let F31 = 24.16
let G31 = G30+F31
let A32 = @dts(2016,9,21)
fmt A32 "%F"
let B32 = 203951
let C32 = 15.208
let D32 = (B32-B31)/C32
let E32 = 2.099
let F32 = 31.92
let G32 = G31+F32
let A33 = @dts(2016,10,1)
fmt A33 "%F"
let B33 = 204195
let C33 = 12.106
let D33 = (B33-B32)/C33
let E33 = 2.059
let F33 = 24.93
let G33 = G32+F33
let A34 = @dts(2016,10,10)
fmt A34 "%F"
let B34 = 204328
let C34 = 6.892
let D34 = (B34-@nval("B",@myrow-1))/C34
let E34 = 1.989
let F34 = 13.71
let G34 = @nval("G",@myrow-1)+F34
let A35 = @dts(2016,11,6)
fmt A35 "%F"
let B35 = 204641
let C35 = 16.596
let D35 = (B35-@nval("B",@myrow-1))/C35
let E35 = 1.999
let F35 = 33.18
let G35 = @nval("G",@myrow-1)+F35
let A36 = @dts(2016,11,25)
fmt A36 "%F"
let B36 = 204889
let C36 = 13.647
let D36 = (B36-@nval("B",@myrow-1))/C36
let E36 = 1.779
let F36 = 24.28
let G36 = @nval("G",@myrow-1)+F36
let A37 = @dts(2016,12,3)
fmt A37 "%F"
let B37 = 205174
let C37 = 14.009
let D37 = (B37-@nval("B",@myrow-1))/C37
let E37 = 1.999
let F37 = 28
let G37 = @nval("G",@myrow-1)+F37
let A38 = @dts(2017,1,22)
fmt A38 "%F"
let B38 = 205361
let C38 = 13.699
let D38 = (B38-@nval("B",@myrow-1))/C38
let E38 = 2.099
let F38 = 28.75
let G38 = @nval("G",@myrow-1)+F38
let A39 = @dts(2017,2,4)
fmt A39 "%F"
let B39 = 205536
let C39 = 9.516
let D39 = (B39-@nval("B",@myrow-1))/C39
let E39 = 2.069
let F39 = 19.69
let G39 = @nval("G",@myrow-1)+F39
let A40 = @dts(2017,2,25)
fmt A40 "%F"
let B40 = 205761
let C40 = 13.078
let D40 = (B40-@nval("B",@myrow-1))/C40
let E40 = 2.079
let F40 = 27.19
let G40 = @nval("G",@myrow-1)+F40
let A41 = @dts(2017,3,2)
fmt A41 "%F"
let B41 = 205901
let C41 = 8.431
let D41 = (B41-@nval("B",@myrow-1))/C41
let E41 = 2.079
let F41 = 17.53
let G41 = @nval("G",@myrow-1)+F41
let A42 = @dts(2017,4,1)
fmt A42 "%F"
let B42 = 206152
let C42 = 13.479
let D42 = (B42-@nval("B",@myrow-1))/C42
let E42 = 2.089
let F42 = 28.16
let G42 = @nval("G",@myrow-1)+F42
let A43 = @dts(2017,4,20)
fmt A43 "%F"
let B43 = 206340
let C43 = 10.166
let D43 = (B43-@nval("B",@myrow-1))/C43
let E43 = 2.199
let F43 = 22.36
let G43 = @nval("G",@myrow-1)+F43
rightstring H43 = "fake record"
let A44 = @dts(2017,5,10)
fmt A44 "%F"
let B44 = 206440
let C44 = 5.166
let D44 = (B44-@nval("B",@myrow-1))/C44
let E44 = 2.199
let F44 = 11.36
let G44 = @nval("G",@myrow-1)+F44
let A45 = @dts(2017,7,26)
fmt A45 "%F"
let B45 = 206478
let C45 = 13.563
let D45 = (B45-@nval("B",@myrow-1))/C45
let E45 = 2.099
let F45 = 28.47
let G45 = @nval("G",@myrow-1)+F45
let A46 = @dts(2017,7,29)
fmt A46 "%F"
let B46 = 206651
let C46 = 7.964
let D46 = (B46-@nval("B",@myrow-1))/C46
let E46 = 2.029
let F46 = 16.16
let G46 = @nval("G",@myrow-1)+F46
let A47 = @dts(2017,8,19)
fmt A47 "%F"
let B47 = 206988
let C47 = 16.466
let D47 = (B47-@nval("B",@myrow-1))/C47
let E47 = 2.169
let F47 = 35.71
let G47 = @nval("G",@myrow-1)+F47
let A48 = @dts(2017,9,9)
fmt A48 "%F"
let B48 = 207299
let C48 = 13.455
let D48 = (B48-@nval("B",@myrow-1))/C48
let E48 = 2.439
let F48 = 32.82
let G48 = @nval("G",@myrow-1)+F48
let A49 = @dts(2017,9,15)
fmt A49 "%F"
let B49 = 207506
let C49 = 10.275
let D49 = (B49-@nval("B",@myrow-1))/C49
let E49 = 2.309
let F49 = 23.72
let G49 = @nval("G",@myrow-1)+F49
let A50 = @dts(2017,9,16)
fmt A50 "%F"
let B50 = 207653
let C50 = 7.278
let D50 = (B50-@nval("B",@myrow-1))/C50
let E50 = 2.409
let F50 = 17.53
let G50 = @nval("G",@myrow-1)+F50
let A51 = @dts(2017,9,30)
fmt A51 "%F"
let B51 = 207884
let C51 = 12.469
let D51 = (B51-@nval("B",@myrow-1))/C51
let E51 = 2.399
let F51 = 29.91
let G51 = @nval("G",@myrow-1)+F51
let A52 = @dts(2017,10,8)
fmt A52 "%F"
let B52 = 208183
let C52 = 14.063
let D52 = (B52-@nval("B",@myrow-1))/C52
let E52 = 2.199
let F52 = 30.92
let G52 = @nval("G",@myrow-1)+F52
let A53 = @dts(2017,10,14)
fmt A53 "%F"
let B53 = 208346
let C53 = 8.623
let D53 = (B53-@nval("B",@myrow-1))/C53
let E53 = 2.359
let F53 = 20.34
let G53 = @nval("G",@myrow-1)+F53
let A54 = @dts(2017,11,6)
fmt A54 "%F"
let B54 = 208636
let C54 = 16.177
let D54 = (B54-@nval("B",@myrow-1))/C54
let E54 = 2.409
let F54 = 38.97
let G54 = @nval("G",@myrow-1)+F54
let A55 = @dts(2017,11,22)
fmt A55 "%F"
let B55 = 208780
let C55 = 7.813
let D55 = (B55-@nval("B",@myrow-1))/C55
let E55 = 2.219
let F55 = 17.34
let G55 = @nval("G",@myrow-1)+F55
let A56 = @dts(2017,11,24)
fmt A56 "%F"
let B56 = 208922
let C56 = 7.619
let D56 = (B56-@nval("B",@myrow-1))/C56
let E56 = 2.379
let F56 = 18.13
let G56 = @nval("G",@myrow-1)+F56
let A57 = @dts(2017,12,2)
fmt A57 "%F"
let B57 = 209114
let C57 = 9.002
let D57 = (B57-@nval("B",@myrow-1))/C57
let E57 = 2.179
let F57 = 19.62
let G57 = @nval("G",@myrow-1)+F57
let A58 = @dts(2018,1,20)
fmt A58 "%F"
let B58 = 209562
let C58 = 12.837
let D58 = (B58-@nval("B",@myrow-1))/C58
let E58 = 2.249
let F58 = 28.87
let G58 = @nval("G",@myrow-1)+F58
let A59 = @dts(2018,2,18)
fmt A59 "%F"
let B59 = 209811
let C59 = 15.578
let D59 = (B59-@nval("B",@myrow-1))/C59
let E59 = 2.399
let F59 = 37.37
let G59 = @nval("G",@myrow-1)+F59
let A60 = @dts(2018,2,18)
fmt A60 "%F"
let B60 = 209932
let C60 = 5.612
let D60 = (B60-@nval("B",@myrow-1))/C60
let E60 = 2.399
let F60 = 13.46
let G60 = @nval("G",@myrow-1)+F60
let A61 = @dts(2018,4,23)
fmt A61 "%F"
let B61 = 210471
let C61 = 16.89
let D61 = (B61-@nval("B",@myrow-1))/C61
let E61 = 2.509
let F61 = 42.38
let G61 = @nval("G",@myrow-1)+F61
let A62 = @dts(2018,9,11)
fmt A62 "%F"
let B62 = 210764
let C62 = 16.711
let D62 = (B62-@nval("B",@myrow-1))/C62
let E62 = 2.609
let F62 = 43.6
let G62 = @nval("G",@myrow-1)+F62
let A63 = @dts(2018,11,1)
fmt A63 "%F"
let B63 = 211013
let C63 = 16.881
let D63 = (B63-@nval("B",@myrow-1))/C63
let E63 = 2.729
let F63 = 46.07
let G63 = @nval("G",@myrow-1)+F63
goto F63 A32
