# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric color
format 5 = "%F"
format A 10 2 5
format B 7 0 0
format C 7 3 0
format D 11 2 0
format E 6 3 0
format F 6 2 0
format H 27 2 0
color 1 = @white;@black
color 7 = @white;@blue
rightstring A0 = "date"
rightstring B0 = "milage"
rightstring C0 = "added"
rightstring D0 = "efficiency"
rightstring E0 = "price"
rightstring F0 = "cost"
rightstring G0 = "total"
let A1 = @dts(2015,11,28)
fmt A1 "%F"
let B1 = 197482
let C1 = 16.626
let D1 = @avg(D2:D3)
let E1 = 1.819
let F1 = 30.24
let G1 = F1
let A2 = @dts(2015,12,5)
fmt A2 "%F"
let B2 = 197665
let C2 = 9.541
let D2 = (B2-B1)/C2
let E2 = 1.899
let F2 = 18.12
let G2 = G1+F2
let A3 = @dts(2015,12,12)
fmt A3 "%F"
let B3 = 197806
let C3 = 7.604
let D3 = (B3-B2)/C3
let E3 = 1.799
let F3 = 13.68
let G3 = G2+F3
let A4 = @dts(2016,1,19)
fmt A4 "%F"
let B4 = 197916
let C4 = 8.928
let D4 = (B4-B3)/C4
let E4 = 1.649
let F4 = 14.72
let G4 = G3+F4
rightstring H4 = "low T, in town, heavy load"
let A5 = @dts(2016,1,19)
fmt A5 "%F"
let B5 = 198031
let C5 = 6.119
let D5 = (B5-B4)/C5
let E5 = 1.649
let F5 = 10.09
let G5 = G4+F5
let A6 = @dts(2016,1,21)
fmt A6 "%F"
let B6 = 198193
let C6 = 8.636
let D6 = (B6-B5)/C6
let E6 = 1.599
let F6 = 13.81
let G6 = G5+F6
let A7 = @dts(2016,1,24)
fmt A7 "%F"
let B7 = 198314
let C7 = 6.304
let D7 = (B7-B6)/C7
let E7 = 1.599
let F7 = 10.08
let G7 = G6+F7
let A8 = @dts(2016,2,13)
fmt A8 "%F"
let B8 = 198414
let C8 = 7.256
let D8 = (B8-B7)/C8
let E8 = 1.349
let F8 = 9.79
let G8 = G7+F8
let A9 = @dts(2016,3,1)
fmt A9 "%F"
let B9 = 198659
let C9 = 12.942
let D9 = (B9-B8)/C9
let E9 = 1.699
let F9 = 21.99
let G9 = G8+F9
let A10 = @dts(2016,3,1)
fmt A10 "%F"
let B10 = 198777
let C10 = 5.907
let D10 = (B10-B9)/C10
let E10 = 1.699
let F10 = 10.04
let G10 = G9+F10
let A11 = @dts(2016,3,5)
fmt A11 "%F"
let B11 = 198853
let C11 = 3.936
let D11 = (B11-B10)/C11
let E11 = 1.659
let F11 = 6.53
let G11 = G10+F11
let A12 = @dts(2016,3,10)
fmt A12 "%F"
let B12 = 199034
let C12 = 8.789
let D12 = (B12-B11)/C12
let E12 = 1.799
let F12 = 15.81
let G12 = G11+F12
let A13 = @dts(2016,3,29)
fmt A13 "%F"
let B13 = 199238
let C13 = 10.041
let D13 = (B13-B12)/C13
let E13 = 1.939
let F13 = 19.47
let G13 = G12+F13
let A14 = @dts(2016,3,31)
fmt A14 "%F"
let B14 = 199348
let C14 = 5.732
let D14 = (B14-B13)/C14
let E14 = 1.939
let F14 = 11.11
let G14 = G13+F14
let A15 = @dts(2016,3,31)
fmt A15 "%F"
let B15 = 199483
let C15 = 8.321
let D15 = (B15-B14)/C15
let E15 = 2.299
let F15 = 19.13
let G15 = G14+F15
let A16 = @dts(2016,3,31)
fmt A16 "%F"
let B16 = 199629
let C16 = 9.029
let D16 = (B16-B15)/C16
let E16 = 1.979
let F16 = 17.87
let G16 = G15+F16
let A17 = @dts(2016,4,2)
fmt A17 "%F"
let B17 = 199823
let C17 = 9.338
let D17 = (B17-B16)/C17
let E17 = 1.879
let F17 = 17.55
let G17 = G16+F17
let A18 = @dts(2016,4,2)
fmt A18 "%F"
let B18 = 200100
let C18 = 13.359
let D18 = (B18-B17)/C18
let E18 = 1.949
let F18 = 26.04
let G18 = G17+F18
let A19 = @dts(2016,4,3)
fmt A19 "%F"
let B19 = 200308
let C19 = 10.052
let D19 = (B19-B18)/C19
let E19 = 1.779
let F19 = 17.88
let G19 = G18+F19
let A20 = @dts(2016,4,30)
fmt A20 "%F"
let B20 = 200542
let C20 = 13.288
let D20 = (B20-B19)/C20
let E20 = 1.889
let F20 = 25.1
let G20 = G19+F20
goto E20 A0
