# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

format A 10 2 3
format B 7 0 0
format C 6 2 0
format D 10 3 0
rightstring A0 = "date"
rightstring B0 = "milage"
rightstring C0 = "cost"
rightstring D0 = "total"
let A1 = @dts(2015,12,6)
let B1 = 197684
let C1 = 35.88
let D1 = C1/1000
goto D1 A0
